### ISSUE TITLE
[Non Issue] Licensing

### ISSUE THREAD

**Issue by funjoker** [wowdev/DBCD#11]
Dear @barncastle, @marlamin and @justMaku,

to make a long story short.
I want to ask if i am allowed to use your DBFileReaderLib inside TrinityCore/WowPacketParser.
Your Library is the onliest working properly.
Since WPP is under GPL and your project has no license.
All copyright lies to you 3 at the moment.
Sadly my friend Seyden stopped developing his library.

Thanks for reading

**Comment by Marlamin** [comment]
Should just go MIT imo, but @barncastle and @justMaku will have to chime in as well.

**Comment by Marlamin** [comment]
Done.

**Comment by funjoker** [comment]
Thank you very much
