### ISSUE TITLE
Old DBCs don't load

### ISSUE THREAD

**Issue by Marlamin** [wowdev/DBCD#4]
e.g. https://wow.tools/dbc/?dbc=map&build=3.3.5.12340

Crashes here because `i` is out of range of the stringtable. https://github.com/wowdev/DBCD/blob/af0f313e6f8632343d8660334bebeb95ecabe5b7/DBFileReaderLib/Readers/WDBCReader.cs#L54

**Comment by barncastle** [comment]
Works for me. Can you share your DBC?

**Comment by Marlamin** [comment]
[map.zip](https://github.com/wowdev/DBCD/files/3667626/map.zip)

**Comment by barncastle** [comment]
Your DBC's header says it has 126 fields which doesn't seem right... Should be 66 according to the definition, WDBX's defs and my copy(?).

**Comment by Marlamin** [comment]
oh no

**Comment by justMaku** [comment]
oh no

**Comment by Marlamin** [comment]
Exported it with MPQ editor as these settings. Is that not right?

![image](https://user-images.githubusercontent.com/50212/65836127-47badb00-e2ef-11e9-8532-3c14d799f469.png)

**Comment by Marlamin** [comment]
Apparently patch MPQs aren't those. RIP. Guess I'll have to re-extract a bunch. Does mean the DBC I uploaded is from -some- 3.x build though.

**Comment by barncastle** [comment]
Sorry was eating. You want to use Merged Mode and open all the MPQs together, the patch MPQs are Cata+ `wow-update*.mpq`. This one looks like it is for 3.0.1/3.0.2 (can't test right now).

MPQEditor might be able to do this via CLI which would be much easier - not sure 🤷‍♂

**Comment by Marlamin** [comment]
Hmk, fair enough. Will close for now.
