### ISSUE TITLE
ReferenceData lookups should use Index

### ISSUE THREAD

**Issue by Marlamin** [wowdev/DBCD#8]
There seems to be an issue with how parent data is being looked up for rows in WDCx (at least). 

TOM_RUS reported the following weird results for ItemEffect on wow.tools.

[ItemID 174457](https://www.wowdb.com/items/174457-cthuffer) (a Battle pet item) before fix:

ID | LegacySlotIndex | TriggerType | Charges | CoolDownMSec | CategoryCoolDownMSec | SpellCategoryID | SpellID | ChrSpecializationID | ParentItemID
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
116156 | 3 | 1 | 0 | -1 | -1 | 0 | 315281 | 0 | 174457
116157 | 4 | 1 | 0 | -1 | -1 | 0 | 315282 | 0 | 174457

Maps it to two consecutive version of the [Strikethrough spell](https://www.wowdb.com/spells/315282-strikethrough) which is nonsense.

Simca suggested changing the following line:
https://github.com/wowdev/DBCD/blob/006c50cdce87572bf8c34eb120c66dab50814e01/DBFileReaderLib/Readers/WDC3Reader.cs#L407

to

```csharp
IDBRow rec = new WDC3Row(this, bitReader, sections[sectionIndex].IndexDataSize != 0 ? m_indexData[i] : -1, refData?.Entries.Where(x => x.Index == i).FirstOrDefault(), i + previousRecordCount);
 ```

which yields the following results:

ID | LegacySlotIndex | TriggerType | Charges | CoolDownMSec | CategoryCoolDownMSec | SpellCategoryID | SpellID | ChrSpecializationID | ParentItemID
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
116161 | 0 | 0 | -1 | -1 | -1 | 0 | 55884 | 0 | 174457
116162 | 1 | 6 | 0 | -1 | -1 | 0 | 315290 | 0 | 174457

..which makes much more sense as those are the SpellIDs for "Learning" as well as the summon spell for the pet itself.

Haven't measured performance with this change, there might be a better way of implementing it, maybe similar to what TOM_RUS does [here](https://github.com/WoW-Tools/CASCExplorer/blob/master/CASCExplorer/WDC3Reader.cs#L268). Hence why this isn't a PR but an issue instead.

**Comment by barncastle** [comment]
OK makes sense, Tom's implementation is exactly what I would've done. I'll
look at this somepoint tomorrow along with the other stuff if no one else
beats me to it.
