### ISSUE TITLE
DB structure should be ignored for ref IDs

### ISSUE THREAD

**Issue by Marlamin** [wowdev/DBCD#9]
As initially reported by Shauren on IRC, it appears that there's an issue with meta sometimes being incorrect for reference IDs. For the WoW client this won't affect it until hotfixes are applied for the larger IDs, but will when they try to hotfix something bigger than what the type is able to contain. Said bug has been reported to Blizz already.

[AzeriteTierUnlock](https://github.com/wowdev/WoWDBDefs/blob/b97a4401af3ea22bab4ee6be899d297a4e08c1a4/definitions/AzeriteTierUnlock.dbd#L14) recently got a reference index value to 274, which is larger than a `uint8` can contain. DBCD crashes here:

https://github.com/wowdev/DBCD/blob/898fb2b458ec4e7ea65847dea94b2b1535fd15ac/DBFileReaderLib/Readers/WDC3Reader.cs#L104 with a rather expected `System.OverflowException: 'Value was either too large or too small for an unsigned byte.'`. 

The most obvious suggestion would be using the original reference ID type of `uint32` instead of trying to convert it to fit in with meta, but this _might_ cause issues for applying hotfixes to reference fields which might need to be handled differently.

**Comment by barncastle** [comment]
You can just add an override in [`FieldDefinitionToType`](https://github.com/wowdev/DBCD/blob/898fb2b458ec4e7ea65847dea94b2b1535fd15ac/DBCD/DBCDBuilder.cs#L150) to achieve this i.e.

```c#
if (field.isRelation)
   return isArray ? typeof(int[]) : typeof(int);
```

I don't think this will have any knock-on effects but then again I've been wrong before!

**Comment by Marlamin** [comment]
@justMaku Would doing that have repercussions on hotfixes?
